### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by ggcaponetto** [Emurgo/message-signing#6]
Hello. I am not familiar with Rust but apparently I have no other option than trying to build it myself.

Running `cargo build` in the `exmples/rust` directory gives me the following error. Any advice would really be appreciated!

```
   Compiling cbor_event v2.1.3
   Compiling cryptoxide v0.2.1
   Compiling bech32 v0.7.3
error[E0518]: attribute should be applied to function or closure
  --> C:\Users\Giuseppe\.cargo\bin\registry\src\github.com-1ecc6299db9ec823\cryptoxide-0.2.1\src\chacha\sse2.rs:38:1
   |
38 | #[inline]
   | ^^^^^^^^^ not a function or closure

   Compiling ed25519 v1.2.0
   Compiling generic-array v0.14.4
   Compiling base64-url v1.4.10
For more information about this error, try `rustc --explain E0518`.
error: could not compile `cryptoxide` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

```

I am looking for the export of ``const {COSESign1, Label} = require("./extra_modules/@emurgo/cardano-message-signing-nodejs");`` as described [here](https://cardano.stackexchange.com/questions/2498/how-to-verify-data-signed-with-nami-wallet-in-a-node-backend, but I am not sure I am on the right track.

**Comment by XuJiandong** [comment]
Try updating cryptoxide to version "0.3.6".

**Comment by ggcaponetto** [comment]
Retried it today with a fresh installation of the rust toolchain on WSL and the building worked.
